#+title: Mi Proyecto
#+author: Miguel Piña
#+author: D. Vega
#+date: [2019-02-19 mar 15:09]

Este es un ejemplo de descripción para mi primer proyecto en git. Seguro
contendrá el modo de uso y un proyecto en Maven

* ¿Cómo compilar el proyecto?

El proyecto se compila haciendo:

#+begin_src sh
mvn clean install
#+end_src


#+begin_src java
public void main(String args[]) {
   System.out.println("Holi");
}
#+end_src

#+begin_src java
public void main(String args[]) {
   System.out.println("HOLA MUNDO");
}
#+end_src

** Como configurar la base de datos
Inicie sesión en la línea de comandos de MySQL. El comando podría ser parecido al siguiente ejemplo:
#+begin_src sql
mysql -u username -ppassword
#+end_src

Para username, especifique el nombre de usuario de MySQL. El nombre de usuario predeterminado es root. Para password, especifique la contraseña del nombre de usuario. La cuenta predeterminada no tiene contraseña; en este caso, omita el distintivo -p y la contraseña. No hay espacio entre el distintivo -p y la contraseña.
Cree una base de datos. 
Cierre la sesión de la línea de mandatos de MySQL.
Obtenga el controlador JDBC de MySQL. El archivo JAR JBDC se incluye entre los archivos de instalación. El controlador es exclusivo para la edición que se utiliza.

Cuando haya varios controladores disponibles, deberá consultar al proveedor de base de datos para determinar qué controlador debe utilizarse. La versión del controlador JDBC que debe utilizarse dependerá de la versión de la base de datos y la versión de Java utilizadas por el servidor de IBM UrbanCode Deploy.

** ¿Qué dependencias son necesarias?
* Estilo de codificación
* Gotchas
